const CollapsibleMenu = () => {
  return (
    <ul className="menu text-neutral lg:menu-horizontal bg-base-100 rounded-box pr-32">
      <li>
        <a>درباره ما</a>
      </li>
      <li>
        <a>تماس با ما</a>
      </li>
      <li>
        <a>فروش ویژه</a>
      </li>
      <li>
        <a>پیگیری</a>
      </li>
      <li>
        <details>
          <summary>زنانه</summary>
          <ul>
            <li>
              <details>
                <summary>لباس</summary>
                <ul>
                  <li>
                    <a>ورزشی</a>
                  </li>
                  <li>
                    <a>رسمی</a>
                  </li>
                  <li>
                    <a>غیره</a>
                  </li>
                </ul>
              </details>
              <details>
                <summary>شلوار</summary>
                <ul>
                  <li>
                    <a>ورزشی</a>
                  </li>
                  <li>
                    <a>رسمی</a>
                  </li>
                  <li>
                    <a>غیره</a>
                  </li>
                </ul>
              </details>
            </li>
          </ul>
        </details>
      </li>
      <li>
        <details>
          <summary>مردانه</summary>
          <ul>
            <li>
              <details>
                <summary>لباس</summary>
                <ul>
                  <li>
                    <a>ورزشی</a>
                  </li>
                  <li>
                    <a>رسمی</a>
                  </li>
                  <li>
                    <a>غیره</a>
                  </li>
                </ul>
              </details>
              <details>
                <summary>شلوار</summary>
                <ul>
                  <li>
                    <a>ورزشی</a>
                  </li>
                  <li>
                    <a>رسمی</a>
                  </li>
                  <li>
                    <a>غیره</a>
                  </li>
                </ul>
              </details>
            </li>
          </ul>
        </details>
      </li>
      <li>
        <details>
          <summary>بچه گانه</summary>
          <ul>
            <li>
              <details>
                <summary>لباس</summary>
                <ul>
                  <li>
                    <a>ورزشی</a>
                  </li>
                  <li>
                    <a>رسمی</a>
                  </li>
                  <li>
                    <a>غیره</a>
                  </li>
                </ul>
              </details>
              <details>
                <summary>شلوار</summary>
                <ul>
                  <li>
                    <a>ورزشی</a>
                  </li>
                  <li>
                    <a>رسمی</a>
                  </li>
                  <li>
                    <a>غیره</a>
                  </li>
                </ul>
              </details>
            </li>
          </ul>
        </details>
      </li>
      <li>
        <a>خانه</a>
      </li>
    </ul>
  );
};
export default CollapsibleMenu;
